name: solar-sha
description: generates a visual reprenstation of a commit's short sha

inputs:
  short-sha: 
    description: commit short sha
    required: true
    default: easter4
  error:
    description: 'The error message to display, if any'
    required: false
    default: ''

outputs:
  error:
    description: 'The description of any error that occurred'
    value: ${{ steps.run.outputs.error }}

runs:
  using: node20
  main: dist/index.js
